name: 'Upgrade version on new release'

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'bump version'
        id: bump
        uses: './.github/actions/semver'
        with:
          current_version: '1.0.2'
      - name: 'print new version'
        run: echo "new version is ${{ steps.bump.outputs.new_version }}"