name: 'Upgrade version on new release'

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: 'bump version'
        id: bump
        uses: './.github/actions/semver.yml'
        with:
          current_version: '1.0.2'
      - name: 'print new version'
        run: echo new version is ${{ bump.outputs.new_version }}